apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h9gy507w6-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-746da25399.un84.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:c35bc8db4266f6abad6c6ddcd8ef3a0e2127f7c5@sha256:2b6300db2c7b7845ae4780a9372d431fccfc01517584617c3e482860563bd9a7
          name: container-image
